### ISSUE TITLE
Follow RealTrainMod English Beta

### ISSUE THREAD

**Issue by hawka97** [hawka97/mcla-mod#13]
Keep up to date with latest betas of RealTrainMod and contribute with comments/bug reports on the mod.

**Comment by hawka97** [comment]
https://www.curseforge.com/minecraft/mc-mods/realtrainmod

**Comment by rinrincodes** [comment]
Needs additional libraries now. Might be bloated. I have another comment that explains more about this in the follow RC roads beta pull request.
