### ISSUE TITLE
Colored Lights Mod - Add or Skip

### ISSUE THREAD

**Issue by hawka97** [hawka97/mcla-mod#16]
https://www.curseforge.com/minecraft/mc-mods/colored-lights

Evaluate and see if we want to have that mod in MCLA.

It requires Albedo, found here: https://minecraft.curseforge.com/projects/albedo?gameCategorySlug=mc-mods&projectID=275300

**Comment by hawka97** [comment]
Won't do in 3.1 - Colored Lights mod too new. Let stabilize

**Comment by rinrincodes** [comment]
Not needed as we have the colored blocks mod that has blocks that light up anyways. Just extra unneeded stuff to load on the server.
