### ISSUE TITLE
Set-up ThutPerms

### ISSUE THREAD

**Issue by hawka97** [hawka97/mcla-mod#17]
The ThutPerms mod is installed on the server, but is not set-up. There will need to be strict permissions on public persons to prevent damage to MCLA.

https://minecraft.curseforge.com/projects/thutperms

**Comment by rinrincodes** [comment]
This mod has been removed as it was giving internal exception errors and messing with a lot of our commands. We don't plan on using it anymore or until it eventually gets fixed.
